version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    build:
      context: .
    environment:
      PGUSER: ${PGUSER}
      PGHOST: ${PGHOST}
      PGPORT: ${PGPORT}
      PGDATABASE: ${PGDATABASE}
      PGPASSWORD: ${PGPASSWORD}
    ports:
      - "3000:3000"
    depends_on:
      - postgres
volumes:
  postgres-data:
